CREATE TABLE IF NOT EXISTS MOVIES (
  id SERIAL PRIMARY KEY,
  title VARCHAR(250) NOT NULL,
  overview VARCHAR(250) NOT NULL,
  popularity FLOAT NOT NULL,
  release_date DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS GENRES (
  id SERIAL PRIMARY KEY,
  name VARCHAR(250) NOT NULL
);

CREATE TABLE IF NOT EXISTS GENRE_MOVIES (
  movie_id INTEGER NOT NULL,
  genre_id INTEGER NOT NULL,
  CONSTRAINT fk_movie
    FOREIGN KEY (movie_id)
      REFERENCES MOVIES(id),
  CONSTRAINT fk_genre
    FOREIGN KEY (genre_id)
      REFERENCES GENRES(id)
);